////// USERS ACTIONS /////

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'


export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const GET_PROFILE_USER = 'GET_PROFILE_USER'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'


export const LOGOUT = 'LOGOUT'


//////  PRODUCTS ACTIONS  /////

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'



export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'





